name: flutter_test_recrutamento
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.5
  flutter_modular: ^4.5.1+1
  mobx: ^2.0.7

dev_dependencies:
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.6
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
